name: magnifying_glass
description: Flutter real-time magnifying glass lens widget with Barrel/Pincushion distortion.
version: 2.1.1
homepage: https://github.com/alnitak/magnifying_glass
issue_tracker: https://github.com/alnitak/magnifying_glass/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: "Magnifying glass logo"
    path: img/screenshot.png

flutter:
